import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { geMe } from "@/data/users";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await geMe()
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserLayout>

          {user.role === "ADMIN" && <nav>Admin Navbar</nav>}
          {user.role === "CUSTOMER" && <nav>Customer Navbar</nav>}
          <nav className="flex gap-4">
            <Link href={'/auth/login'} >Login</Link>
            <Link href={'/auth/register'}>Register</Link>
            <Link href={'/profile'}>Profile</Link>
            <Link href={'/admin'}>Admin</Link>
          </nav>
          {children}
        </UserLayout>

      </body>
    </html>
  );
}


